trigger:
  - main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: e2e_tests
    displayName: "Testes E2E"
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
      - task: UseNode@1
        inputs:
          version: '22.x'
      - script: npm install -g yarn
        displayName: "Instalando Yarn"
      - script: yarn
        displayName: "Instalando dependências"
      - script: yarn playwright install
        displayName: "Instalando Playwright"
      - script: yarn run e2e
        displayName: "Executando testes E2E"